Azure-Samples/azure-intelligent-edge-patterns

GpuReferenceModules/ReadMe.md
GpuReferenceModules/SampleSolution/deployment.template.json
GpuReferenceModules/SampleSolution/modules/GPUModule/main.py
GpuReferenceModules/SampleSolution/modules/GPUModule/module.json
GpuReferenceModules/SampleSolution/modules/GPUModule/utility.py

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

editing readme

---

rras-ike-vnet-vnet/azuredeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

fixing route table

---

rras-gre-vnet-vnet/azuredeploy.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

gre route table

---

VisionOnEdge/ReadMe.md
VisionOnEdge/cameras/models.py
VisionOnEdge/cameras/views.py
VisionOnEdge/requirements.txt
VisionOnEdge/ui/src/components/CameraConfigure/CameraConfigureInfo.tsx
VisionOnEdge/ui/src/components/CapturePhoto/CapturePhotos.tsx
VisionOnEdge/ui/src/components/LabelingPage/Scene.tsx
VisionOnEdge/ui/src/components/UploadPhotos/UploadPhotos.tsx
VisionOnEdge/ui/src/components/UploadPhotos/index.tsx
VisionOnEdge/ui/src/hooks/useInterval.ts
VisionOnEdge/ui/src/pages/LabelingPage.tsx
VisionOnEdge/ui/src/pages/PartDetails.tsx
VisionOnEdge/ui/src/pages/PartIdentification.tsx
VisionOnEdge/ui/src/pages/Parts.tsx
VisionOnEdge/ui/src/store/labelingPage/labelingPageActions.ts
VisionOnEdge/ui/src/store/labelingPage/labelingPageReducer.ts
VisionOnEdge/ui/src/store/labelingPage/labelingPageTypes.ts
VisionOnEdge/ui/src/store/part/partActions.ts
VisionOnEdge/ui/src/store/part/partReducer.ts
VisionOnEdge/ui/src/store/part/partTypes.ts
VisionOnEdge/vision_on_edge/urls.py

Add training, and export model feature

Yadam newrepo

---

GpuReferenceModules/ReadMe.md
GpuReferenceModules/SampleSolution/modules/GPUModule/module.json

updating read me for gpu reference module
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updating Read me Doc

---

fhir-server-edge/azure-pipelines.yml
fhir-server-edge/azure-stack-edge/deployment.template.json
fhir-server-edge/azure-stack-edge/run_tests.sh
fhir-server-edge/azure-stack-hub/.env.template
fhir-server-edge/azure-stack-hub/helm/fhirk8s/templates/fhir-server-deployment.yaml
fhir-server-edge/azure-stack-hub/helm/fhirk8s/templates/mssql-pvc.yaml
fhir-server-edge/azure-stack-hub/helm/fhirk8s/values.yaml
fhir-server-edge/azure-stack-hub/run_tests.sh

- adding testing shell scripts
- adding azure-pipelines.yaml
- updating templates where necessary
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x] Feature
```
*  Create Azure Pipeline pointing to azure-pipelines.yaml file in this change set
* Upload .env file and certificate as secret files in Azure Pipelines
* Trigger a pipeline run
* **NOTE:** pipeline assumes you already have an AKS cluster and an IoT edge VM for deploying into

Creating CI Pipeline with Azure Pipelines

---

factory-ai-vision/Installers-dev/Windows/deployment.amd64.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Yadam newrepo, fix deploymentjson

---

factory-ai-vision/EdgeSolution/deployment.gpu.template.json
factory-ai-vision/EdgeSolution/modules/InferenceModule/module.json
factory-ai-vision/EdgeSolution/modules/WebModule/backend/cameras/apps.py
factory-ai-vision/EdgeSolution/modules/WebModule/module.json
factory-ai-vision/Installers-dev/Windows/deployment.amd64.json
factory-ai-vision/Installers-dev/bash/deployment.amd64.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Yadam newrepo: fix environment variable issue

---

Research/mlflow-on-azure-stack/notebooks/MLflow_Tutorial.ipynb

* Comments and calls out areas that are still in development 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```

Updating Jupyter Notebook

---

Research/kubeflow-on-azure-stack/Readme.md
Research/kubeflow-on-azure-stack/docker/Docker
Research/kubeflow-on-azure-stack/docker/build_and_run.sh
Research/kubeflow-on-azure-stack/docker/main.py
Research/kubeflow-on-azure-stack/docker/run_in_k8s.sh
Research/kubeflow-on-azure-stack/docker/simple_tf_mnist.yaml
Research/kubeflow-on-azure-stack/installing_kubernetes.md
Research/kubeflow-on-azure-stack/installing_storage.md
Research/kubeflow-on-azure-stack/introduction_to_docker.md
Research/kubeflow-on-azure-stack/tensorflow-on-kubeflow/Readme.md

This PR
* Several additions and updates in `kubeflow-on-azure-stack` section
* Simple Docker demo as a first step in the tutorial based on kubeflow-on-azure-stack section.
```
[ ] Yes
[N] No
```
```
[ ] Bugfix
[X] Feature
[X] Documentation content changes
```
```
cd [repo-name]
npm install
```
The instructions in kubeflow-on-azure-stack should be reproducible
```
```
* the new Docker Intro files should create an image and be runnable

Kubeflow doc updates, and docker into subpage

---

subscription replicator/Scripts/resource_retriever.ps1

* This PR adds a fix when querying the resource type `Microsoft.Network/networkSecurityGroups`. Currently, `Get-AzureRmResource`'s API discovery selects the API version `2016-09-01` which is missing data in the JSON response such as:
```
"destinationPortRanges": [
"80",
"443",
"6060",
"8080"
],
"sourceAddressPrefixes": [
"10.192.1.0/27",
"10.203.0.0/16"
],
```
To fix this, we check if the resource is `Microsoft.Network/networkSecurityGroups` and force a specific API version of `2017-10-01` which contains the missing data.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] Other... Please …
```

Add fix for resource type Microsoft.Network/networkSecurityGroups missing data

---

GpuReferenceModules/SampleSolution/deployment.k8s.template.json

* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add K8s deployment for getting started with gpu sample

---

factory-ai-vision/EdgeSolution/modules/InferenceModule/sort.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/tracker.py

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Factory AI Update (add tracker)

---

factory-ai-vision/EdgeSolution/modules/InferenceModule/config.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/dockerfiles/Dockerfile.cpuamd64
factory-ai-vision/EdgeSolution/modules/InferenceModule/dockerfiles/Dockerfile.gpuamd64
factory-ai-vision/EdgeSolution/modules/InferenceModule/inference_engine.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/main.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/module.json
factory-ai-vision/EdgeSolution/modules/InferenceModule/scenario_models/3/labels.txt
factory-ai-vision/EdgeSolution/modules/InferenceModule/scenarios.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/server.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/stream_manager.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/streams.py
factory-ai-vision/EdgeSolution/modules/InferenceModule/tracker.py
factory-ai-vision/EdgeSolution/modules/WebModule/backend_v2/vision_on_edge/azure_parts/apps.py
factory-ai-vision/EdgeSolution/modules/WebModule/module.json
factory-ai-vision/EdgeSolution/modules/WebModule/ui_v2/src/components/CaptureDialog.tsx
factory-ai-vision/EdgeSolution/modules/WebModule/ui_v2/src/store/cameraSlice.ts
factory-ai-vision/EdgeSolution/modules/WebModule/ui_v2/src/store/scenarioSlice.ts

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update Factory AI

---

Research/deploying-model-on-k8s/Readme.md
Research/deploying-model-on-k8s/production-deploy-to-k8s-gpu.ipynb

* This PR addresses some usability feedback for Azure ML model deployment on Kubernetes cluster using a Jupyter notebook.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
Follow the instructions and run through the `Research/production-deploy-to-k8s-gpu.ipynb`
```
* You should be able to create a model and deploy it to a Kubernetes cluster.

Updates to k8s model deployment

---

factory-ai-vision/Readme.md

Fixing a couple of typos in the readme
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

correcting typo

---

Research/kubeflow-on-azure-stack-lab/04-KFServing/Readme.md
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/Readme.md
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert.yaml
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_large/config.pbtxt
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/Dockerfile
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/bert_transformer/__main__.py
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/bert_transformer/bert_transformer.py
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/bert_transformer/data_processing.py
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/bert_transformer/tokenization.py
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_bert_tokenizer/setup.py
Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/triton_input.json

* Adding chapter to kubeflow-on-azure-stack KFServing InferenceService using Triton Nvidia server
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[X] Documentation content changes
```
```
cd [repo-name]
npm install
```
Follow the instructions in `Research/kubeflow-on-azure-stack-lab/04-KFServing/triton/Readme.md`
```
```
* You should be able to run BERT inferences as the tutorial describes

Adding tutorial on KFServing InferenceService using Triton Nvidia server.

---

edge-knowledge-mining/Readme.md

Introducing a new edge pattern for Knowledge Mining
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

edge-knowledge-mining introduction

---

fhir-server-edge/azure-stack-edge/Readme.md
fhir-server-edge/azure-stack-edge/deployment.template.json

* Fixed a typo in the deployment.template.json, changed "Env" to "env".
* Added a bullet point in Readme.md to make sure the shares are mounted as PVs.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
*  Open deployment.template.json in VS Code, generate the deployment manifest and deploy to a single edge device.
```
cd [repo-name]
code .
```
```
Execute kubectl get pv, and verify the PVs are available in k8s cluster.
```
* Verify you can successfully generate …

Rick jen bugfix patch

---

factory-ai-vision/Tutorial/VoE_Helm_Chart.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

updating master

---

AKSe-on-AzStackHub/src/tf/aksengine/README.md

Fix broken image links in a readme
```
[ ] Yes
[X] No
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix image links

---

README.md
factory-ai-vision/Deploy/arm/README.md
factory-ai-vision/Deploy/arm/armdeploy.json
factory-ai-vision/Deploy/arm/one-click-armdeploy.json
factory-ai-vision/Readme.md
factory-ai-vision/Tutorial/Shell-installer-Tutorial.md
factory-ai-vision/Tutorial/Tutorial_ARM_TemplateDeployment.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updating VoE Docs

---

README.md

* ...
```bash
cd [repo-name]
npm install
```
```bash
npm run test
```
* All tests shall pass.

Rlfmendes patch 1
